### ISSUE TITLE
Add support for self-signed certificates

### ISSUE THREAD

**Issue by silversquirl** [k0rmarun/pyweechat#1]
Currently, when asked to connect using SSL to a weechat relay with a self-signed certificate, the following error is raised:

    ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)

It'd be nice if there was an option to either a) modify the SSL context in some way before connecting (perhaps using a callback?) or b) add certs from non-default locations (using [`load_verify_locations`][python_ssl_lvl] internally. Ideally `cafile`, `capath` and `cadata` would all be supported).

[python_ssl_lvl]: https://docs.python.org/3/library/ssl.html#ssl.SSLContext.load_verify_locations

**Comment by k0rmarun** [comment]
Well for using cheap certificates, there is LetsEncrypt. 
But restricting possible certs sounds like an good idea anyway. Will be doing this this weekend.

**Comment by silversquirl** [comment]
Let's Encrypt is great, sure, but it's a lot harder to set up. For those who can't be bothered (like myself!) this would be a nice feature to have. It should definitely be controlled though; people should have to explicitly add every self-signed cert they want to allow, otherwise it's a security risk.

Thanks for looking at this!

**Comment by k0rmarun** [comment]
Hmm, might be a while until this update appears in pypi, as i suffer from https://github.com/pypa/pypi-legacy/issues/675
